refactor: merge files to save lines of code
morpho-org/morpho-token-upgradeable pull request #3
Opened 2024-10-12 15:27 UTC by MerlinEgalite

2024-10-15 08:16 UTC, Jean-Grimal commented
I think I would rather keep the two files

2024-10-15 17:38 UTC, MerlinEgalite commented
> I think I would rather keep the two files

Why? I think it's unnecessary since for the following reasons:
- It's adding more LOC 
- We're not going to reuse any of those 2 files in other protocols

2024-10-16 08:47 UTC, MerlinEgalite commented on src/ERC20DelegatesUpgradeable.sol
> +        // No check of supply cap here like in OZ implementation has MORPHO has a 1B total supply cap.
```suggestion
        // No check of supply cap here like in OZ implementation as MORPHO has a 1B total supply cap.
```

2024-10-16 08:59 UTC, Jean-Grimal requested changes

2024-10-16 08:59 UTC, Jean-Grimal commented on src/ERC20DelegatesUpgradeable.sol
> +    function _getDelegatesStorage() private pure returns (ERC20DelegatesStorage storage $) {
```suggestion
    function _getERC20DelegatesStorage() private pure returns (ERC20DelegatesStorage storage $) {
```

2024-10-16 08:59 UTC, Jean-Grimal commented on src/ERC20DelegatesUpgradeable.sol
> +        ERC20DelegatesStorage storage $ = _getDelegatesStorage();
```suggestion
        ERC20DelegatesStorage storage $ = _getERC20DelegatesStorage();
```

2024-10-16 08:59 UTC, Jean-Grimal commented on src/ERC20DelegatesUpgradeable.sol
> +        ERC20DelegatesStorage storage $ = _getDelegatesStorage();
```suggestion
        ERC20DelegatesStorage storage $ = _getERC20DelegatesStorage();
```

2024-10-16 08:59 UTC, Jean-Grimal commented on src/ERC20DelegatesUpgradeable.sol
> +        ERC20DelegatesStorage storage $ = _getDelegatesStorage();
```suggestion
        ERC20DelegatesStorage storage $ = _getERC20DelegatesStorage();
```

2024-10-16 08:59 UTC, Jean-Grimal commented on src/ERC20DelegatesUpgradeable.sol
> +        ERC20DelegatesStorage storage $ = _getDelegatesStorage();
```suggestion
        ERC20DelegatesStorage storage $ = _getERC20DelegatesStorage();
```

2024-10-16 08:59 UTC, Jean-Grimal commented on src/ERC20DelegatesUpgradeable.sol
> +        ERC20DelegatesStorage storage $ = _getDelegatesStorage();
```suggestion
        ERC20DelegatesStorage storage $ = _getERC20DelegatesStorage();
```

2024-10-16 08:59 UTC, Jean-Grimal commented on src/ERC20DelegatesUpgradeable.sol
> +        ERC20DelegatesStorage storage $ = _getDelegatesStorage();
```suggestion
        ERC20DelegatesStorage storage $ = _getERC20DelegatesStorage();
```

2024-10-16 09:03 UTC, merged