Fix N-05
morpho-org/morpho-token-upgradeable pull request #70
Opened 2024-10-28 15:56 UTC by Jean-Grimal

Fixes https://defender.openzeppelin.com/#/audit/0ed5cb02-a980-4c27-8890-d74c15e0438c/issues/N-05

2024-10-28 16:30 UTC, MathisGD approved these changes

2024-10-28 16:34 UTC, colin-morpho approved these changes

2024-10-28 16:42 UTC, QGarchery requested changes
We

2024-10-28 16:42 UTC, QGarchery commented on src/MorphoTokenEthereum.sol
We can remove the following line as well:
```solidity
require(owner != address(0), ZeroAddress());
```

2024-10-28 16:46 UTC, colin-morpho commented on src/MorphoTokenEthereum.sol
Implemented in https://github.com/morpho-org/morpho-token-upgradeable/pull/70/commits/ee003565bfbd692c5ced781661bd223cf6689917.

2024-10-28 16:59 UTC, colin-morpho approved these changes

2024-10-28 17:05 UTC, MerlinEgalite requested changes

2024-10-28 17:05 UTC, MerlinEgalite commented on src/MorphoTokenEthereum.sol
> -        require(owner != address(0), ZeroAddress());
The error can be removed I think

2024-10-28 17:06 UTC, MerlinEgalite commented on src/MorphoTokenEthereum.sol
> -        require(owner != address(0), ZeroAddress());
wait just seeing [this](https://github.com/morpho-org/morpho-token-upgradeable/pull/70#discussion_r1819398451) but i can't find the changes

2024-10-28 17:07 UTC, MerlinEgalite commented
branch name is fix/n-05 while it's fixing N-067 which is super confusing

2024-10-29 08:56 UTC, Jean-Grimal commented
> branch name is `fix/n-05` while it's fixing N-067 which is super confusing

Yes I did a mistake in the naming

2024-10-29 09:18 UTC, QGarchery commented on src/MorphoTokenEthereum.sol
Let's also remove the `ZeroAddress` error in this contract

2024-10-29 09:55 UTC, QGarchery approved these changes

2024-10-29 09:56 UTC, MerlinEgalite approved these changes

2024-10-29 10:10 UTC, MathisGD approved these changes

2024-10-29 14:35 UTC, merged